# Generated by Django 6.0.4 on 2026-04-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationSetting',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='key')),
                ('value', models.TextField(help_text='All values are stored as strings. Type casting happens in the service layer.', verbose_name='value')),
            ],
            options={
                'verbose_name': 'application setting',
                'verbose_name_plural': 'application settings',
            },
        ),
    ]
