# Generated by Django 6.0.4 on 2026-04-23 20:56

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('recharge', 'Recharge'), ('checkin', 'Check-in')], db_index=True, max_length=20, verbose_name='type')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='amount')),
                ('notes', models.TextField(blank=True, default='', help_text='Optional context for the audit trail.', verbose_name='notes')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='created at')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='customers.customer', verbose_name='customer')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_type', 'created_at'], name='ix_tx_type_created_at'), models.Index(fields=['created_at'], name='ix_tx_created_at')],
            },
        ),
    ]
