# Generated by Django 6.0.4 on 2026-04-23 20:56

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='UUID used in API responses. Not the database primary key.', unique=True, verbose_name='public ID')),
                ('name', models.CharField(max_length=150, verbose_name='full name')),
                ('balance', models.DecimalField(decimal_places=2, default='0.00', help_text='Current prepaid balance in the local currency.', max_digits=10, verbose_name='balance')),
                ('qr_id', models.UUIDField(db_index=True, default=uuid.uuid4, help_text="UUID encoded in the customer's physical QR code.", unique=True, verbose_name='QR code ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='registered at')),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='ix_customer_name')],
            },
        ),
    ]
